server:
  port: 8081 #端口号
  servlet:
    context-path: /spring-boot #应用名
#数据源配置
spring:
  datasource:
    username: root
    password: 1234
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatis
#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*DaoMapper.xml